server.port=8085

spring.datasource.url=jdbc:postgresql://187.77.184.71:5432/projectdb?timezone=UTC
spring.datasource.username=projectuser
spring.datasource.password=strongpassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Timezone configuration
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jackson.time-zone=UTC

# HikariCP configuration to disable autoCommit
spring.datasource.hikari.auto-commit=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Cashfree Payment Gateway Configuration
cashfree.api.url=${CASHFREE_BASE_URL:sandbox}
cashfree.api.version=2023-08-01
cashfree.app.id=${CASHFREE_APP_ID:TEST10945021166bff565c92da5f192d12054901}
cashfree.secret.key=${CASHFREE_SECRET_KEY:cfsk_ma_test_c7f4402b544346ebb2506f88cf0db1d4_560e4a99}
cashfree.webhook.url=https://api.rajyadu.in/api/payments/webhook

# Logistics API Configuration

logistic.api.key=b449719be3166a2c26d9e045448d9402
logistic.api.secret=b8c8749c4c87e124a159ecd46b84f2ff
logistic.api.base-url=https://my.ithinklogistics.com
logistic.pickup.pincode=301705
logistic.pickup.address-id=113992
logistic.return.address-id=113992

app.upload.dir=uploads

# SMS Configuration
sms.api.url=https://mdssend.in/api.php
sms.api.username=dhudaramsonsorganic
sms.api.key=GwVIxD9vknhy
sms.api.senderid=MOBTIN
sms.api.route=OTP

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME:}
spring.mail.password=${EMAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# CORS Configuration
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true
